### ISSUE TITLE
Create Search Route for Attractions

### ISSUE THREAD

**Issue by PhamelaMhlaba** [High-Table-Consortium/fullstack-capstone-dockerized#27]
**Description:**

Implement the route to search for attractions and destinations based on user input. This  functionality will allow users to find attractions by keywords, location, and category.

**Tasks:** 

- [ ] **Route:** GET /attractions/search
**Parameters:**
**query (string):** The search keyword (e.g., "museum").
**location (optional, string):** Location to filter by (e.g., "Paris").
**category (optional, string):** Category to filter by (e.g., "historical").
**Response:** List of attractions matching the search criteria.
**Functionality:** Implement search and filtering logic based on the parameters.

**Acceptance Criteria:**

- Route returns a list of attractions in response to search queries.

- Proper error handling for invalid or missing parameters.

- Search should be case-insensitive.

**Comment by NtokozoMitchell** [comment]
endpoint Details-Method :Get
path:/api/search
query parameters: 

- q(required):the search query string
- type:filter by type (sestination or attration)
-
