### ISSUE TITLE
Implement Comment Functionality for Attraction Sites

### ISSUE THREAD

**Issue by Tumelo2748** [High-Table-Consortium/fullstack-capstone-dockerized#71]
## Description:
We need to implement the functionality for managing comments related to attraction sites. This includes creating, updating, deleting, and retrieving comments by attraction site and user.

### The following tasks need to be completed:

---

### **1. Create Comment**:
- **Endpoint**: `POST /comments`
- **Validations**:
  - `userId`: must be a non-empty string
  - `attractionSiteId`: must be a non-empty string
  - `content`: must be a non-empty string
- **Response**: Returns the created comment with a `201` status code.

---

### **2. Get Comments by Attraction Site**:
- **Endpoint**: `GET /comments/attraction/:attractionId`
- **Validations**:
  - `attractionSiteId`: must be a non-empty string
- **Response**: Returns the comments for the specified attraction site with a `200` status code.

---

### **3. Get Comments by User**:
- **Endpoint**: `GET /comments/user/:userId`
- **Validations**:
  - `userId`: must be a non-empty string
- **Response**: Returns the comments for the specified user with a `200` status code.

---

### **4. Update Comment**:
- **Endpoint**: `PUT /comments/:commentId`
- **Validations**:
  - `commentId`: must be a non-empty string
  - `content`: must be a non-empty string
- **Response**: Returns the updated comment with a `200` status code.

---

### **5. Delete Comment**:
- **Endpoint**: `DELETE /comments/:commentId`
- **Validations**:
  - `commentId`: must be a non-empty string
- **Response**: Returns a `204` status code indicating successful deletion.

---

## Acceptance Criteria:
- All endpoints should be implemented as described.
- Proper validation should be in place for each endpoint.
- Appropriate error handling should be implemented.
- Unit tests should be written for each endpoint (Optional).

**Comment by NtokozoMitchell** [comment]
This is a good description.
